package com.official.bean;

import com.official.tree.TreeEntitys;

public class Column extends TreeEntitys<Column> {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_column.id
     *
     * @mbg.generated Thu Mar 19 10:58:50 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_column.columnName
     *
     * @mbg.generated Thu Mar 19 10:58:50 CST 2020
     */
    private String columnName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_column.parent_id
     *
     * @mbg.generated Thu Mar 19 10:58:50 CST 2020
     */
    private Integer parent_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_column.refNo
     *
     * @mbg.generated Thu Mar 19 10:58:50 CST 2020
     */
    private String refNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_column.linkType
     *
     * @mbg.generated Thu Mar 19 10:58:50 CST 2020
     */
    private Integer linkType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_column.linkUrl
     *
     * @mbg.generated Thu Mar 19 10:58:50 CST 2020
     */
    private String linkUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_column.template
     *
     * @mbg.generated Thu Mar 19 10:58:50 CST 2020
     */
    private String template;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_column.columnPreview
     *
     * @mbg.generated Thu Mar 19 10:58:50 CST 2020
     */
    private String columnPreview;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_column.addContent
     *
     * @mbg.generated Thu Mar 19 10:58:50 CST 2020
     */
    private Integer addContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_column.isHidden
     *
     * @mbg.generated Thu Mar 19 10:58:50 CST 2020
     */
    private Integer isHidden;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_column.remark
     *
     * @mbg.generated Thu Mar 19 10:58:50 CST 2020
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_column.sortNum
     *
     * @mbg.generated Thu Mar 19 10:58:50 CST 2020
     */
    private Integer sortNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_column.id
     *
     * @return the value of t_column.id
     *
     * @mbg.generated Thu Mar 19 10:58:50 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_column.id
     *
     * @param id the value for t_column.id
     *
     * @mbg.generated Thu Mar 19 10:58:50 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_column.columnName
     *
     * @return the value of t_column.columnName
     *
     * @mbg.generated Thu Mar 19 10:58:50 CST 2020
     */
    public String getColumnName() {
        return columnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_column.columnName
     *
     * @param columnName the value for t_column.columnName
     *
     * @mbg.generated Thu Mar 19 10:58:50 CST 2020
     */
    public void setColumnName(String columnName) {
        this.columnName = columnName == null ? null : columnName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_column.parent_id
     *
     * @return the value of t_column.parent_id
     *
     * @mbg.generated Thu Mar 19 10:58:50 CST 2020
     */
    public Integer getParent_id() {
        return parent_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_column.parent_id
     *
     * @param parent_id the value for t_column.parent_id
     *
     * @mbg.generated Thu Mar 19 10:58:50 CST 2020
     */
    public void setParent_id(Integer parent_id) {
        this.parent_id = parent_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_column.refNo
     *
     * @return the value of t_column.refNo
     *
     * @mbg.generated Thu Mar 19 10:58:50 CST 2020
     */
    public String getRefNo() {
        return refNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_column.refNo
     *
     * @param refNo the value for t_column.refNo
     *
     * @mbg.generated Thu Mar 19 10:58:50 CST 2020
     */
    public void setRefNo(String refNo) {
        this.refNo = refNo == null ? null : refNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_column.linkType
     *
     * @return the value of t_column.linkType
     *
     * @mbg.generated Thu Mar 19 10:58:50 CST 2020
     */
    public Integer getLinkType() {
        return linkType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_column.linkType
     *
     * @param linkType the value for t_column.linkType
     *
     * @mbg.generated Thu Mar 19 10:58:50 CST 2020
     */
    public void setLinkType(Integer linkType) {
        this.linkType = linkType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_column.linkUrl
     *
     * @return the value of t_column.linkUrl
     *
     * @mbg.generated Thu Mar 19 10:58:50 CST 2020
     */
    public String getLinkUrl() {
        return linkUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_column.linkUrl
     *
     * @param linkUrl the value for t_column.linkUrl
     *
     * @mbg.generated Thu Mar 19 10:58:50 CST 2020
     */
    public void setLinkUrl(String linkUrl) {
        this.linkUrl = linkUrl == null ? null : linkUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_column.template
     *
     * @return the value of t_column.template
     *
     * @mbg.generated Thu Mar 19 10:58:50 CST 2020
     */
    public String getTemplate() {
        return template;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_column.template
     *
     * @param template the value for t_column.template
     *
     * @mbg.generated Thu Mar 19 10:58:50 CST 2020
     */
    public void setTemplate(String template) {
        this.template = template == null ? null : template.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_column.columnPreview
     *
     * @return the value of t_column.columnPreview
     *
     * @mbg.generated Thu Mar 19 10:58:50 CST 2020
     */
    public String getColumnPreview() {
        return columnPreview;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_column.columnPreview
     *
     * @param columnPreview the value for t_column.columnPreview
     *
     * @mbg.generated Thu Mar 19 10:58:50 CST 2020
     */
    public void setColumnPreview(String columnPreview) {
        this.columnPreview = columnPreview == null ? null : columnPreview.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_column.addContent
     *
     * @return the value of t_column.addContent
     *
     * @mbg.generated Thu Mar 19 10:58:50 CST 2020
     */
    public Integer getAddContent() {
        return addContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_column.addContent
     *
     * @param addContent the value for t_column.addContent
     *
     * @mbg.generated Thu Mar 19 10:58:50 CST 2020
     */
    public void setAddContent(Integer addContent) {
        this.addContent = addContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_column.isHidden
     *
     * @return the value of t_column.isHidden
     *
     * @mbg.generated Thu Mar 19 10:58:50 CST 2020
     */
    public Integer getIsHidden() {
        return isHidden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_column.isHidden
     *
     * @param isHidden the value for t_column.isHidden
     *
     * @mbg.generated Thu Mar 19 10:58:50 CST 2020
     */
    public void setIsHidden(Integer isHidden) {
        this.isHidden = isHidden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_column.remark
     *
     * @return the value of t_column.remark
     *
     * @mbg.generated Thu Mar 19 10:58:50 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_column.remark
     *
     * @param remark the value for t_column.remark
     *
     * @mbg.generated Thu Mar 19 10:58:50 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_column.sortNum
     *
     * @return the value of t_column.sortNum
     *
     * @mbg.generated Thu Mar 19 10:58:50 CST 2020
     */
    public Integer getSortNum() {
        return sortNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_column.sortNum
     *
     * @param sortNum the value for t_column.sortNum
     *
     * @mbg.generated Thu Mar 19 10:58:50 CST 2020
     */
    public void setSortNum(Integer sortNum) {
        this.sortNum = sortNum;
    }
}