package com.official.bean;

public class Composition {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_composition.id
     *
     * @mbggenerated Sat Oct 12 14:42:14 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_composition.columnId
     *
     * @mbggenerated Sat Oct 12 14:42:14 CST 2019
     */
    private Integer columnid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_composition.attachUrl
     *
     * @mbggenerated Sat Oct 12 14:42:14 CST 2019
     */
    private String attachurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_composition.name
     *
     * @mbggenerated Sat Oct 12 14:42:14 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_composition.count
     *
     * @mbggenerated Sat Oct 12 14:42:14 CST 2019
     */
    private Integer counts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_composition.employeeId
     *
     * @mbggenerated Sat Oct 12 14:42:14 CST 2019
     */
    private Integer employeeid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_composition.id
     *
     * @return the value of t_composition.id
     *
     * @mbggenerated Sat Oct 12 14:42:14 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_composition.id
     *
     * @param id the value for t_composition.id
     *
     * @mbggenerated Sat Oct 12 14:42:14 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_composition.columnId
     *
     * @return the value of t_composition.columnId
     *
     * @mbggenerated Sat Oct 12 14:42:14 CST 2019
     */
    public Integer getColumnid() {
        return columnid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_composition.columnId
     *
     * @param columnid the value for t_composition.columnId
     *
     * @mbggenerated Sat Oct 12 14:42:14 CST 2019
     */
    public void setColumnid(Integer columnid) {
        this.columnid = columnid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_composition.attachUrl
     *
     * @return the value of t_composition.attachUrl
     *
     * @mbggenerated Sat Oct 12 14:42:14 CST 2019
     */
    public String getAttachurl() {
        return attachurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_composition.attachUrl
     *
     * @param attachurl the value for t_composition.attachUrl
     *
     * @mbggenerated Sat Oct 12 14:42:14 CST 2019
     */
    public void setAttachurl(String attachurl) {
        this.attachurl = attachurl == null ? null : attachurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_composition.name
     *
     * @return the value of t_composition.name
     *
     * @mbggenerated Sat Oct 12 14:42:14 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_composition.name
     *
     * @param name the value for t_composition.name
     *
     * @mbggenerated Sat Oct 12 14:42:14 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_composition.count
     *
     * @return the value of t_composition.count
     *
     * @mbggenerated Sat Oct 12 14:42:14 CST 2019
     */
    public Integer getCounts() {
        return counts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_composition.count
     *
     * @param counts the value for t_composition.count
     *
     * @mbggenerated Sat Oct 12 14:42:14 CST 2019
     */
    public void setCounts(Integer counts) {
        this.counts = counts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_composition.employeeId
     *
     * @return the value of t_composition.employeeId
     *
     * @mbggenerated Sat Oct 12 14:42:14 CST 2019
     */
    public Integer getEmployeeid() {
        return employeeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_composition.employeeId
     *
     * @param employeeid the value for t_composition.employeeId
     *
     * @mbggenerated Sat Oct 12 14:42:14 CST 2019
     */
    public void setEmployeeid(Integer employeeid) {
        this.employeeid = employeeid;
    }
}