package com.official.bean;

import java.sql.Timestamp;

import com.fasterxml.jackson.annotation.JsonFormat;

public class Link {
    
    private Integer id;

    //链接名称
    private String linkname;

    //链接位置名称
    private String linkposition;

    //图片路径
    private String picturepath;

    //链接类型(0:间接链接,1:直接链接)
    private Integer linktype;

    //链接地址
    private String linkurl;

    //发布时间
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Timestamp pubtime;

   //发布时间类型(0:立刻发布,1:自定义)
    private Integer pubtimetype;

    //过期时间
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Timestamp expiredtime;

  //过期时间类型(0:立刻发布,1:自定义)
    private Integer expiredTimeType;

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("Link [id=").append(id).append(", linkname=").append(linkname).append(", linkposition=")
				.append(linkposition).append(", picturepath=").append(picturepath).append(", linktype=")
				.append(linktype).append(", linkurl=").append(linkurl).append(", pubtime=").append(pubtime)
				.append(", pubtimetype=").append(pubtimetype).append(", expiredtime=").append(expiredtime)
				.append(", expiredTimeType=").append(expiredTimeType).append(", isshow=").append(isshow)
				.append(", orderid=").append(orderid).append(", remark=").append(remark).append(", status=")
				.append(status).append("]");
		return builder.toString();
	}

	//是否显示
    private Integer isshow;

    //排序值
    private Integer orderid;

    //备注
    private String remark;

    //类型(0:图片链接,1:文本链接)
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_link.id
     *
     * @return the value of t_link.id
     *
     * @mbggenerated Mon Jan 28 09:38:24 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_link.id
     *
     * @param id the value for t_link.id
     *
     * @mbggenerated Mon Jan 28 09:38:24 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_link.linkName
     *
     * @return the value of t_link.linkName
     *
     * @mbggenerated Mon Jan 28 09:38:24 CST 2019
     */
    public String getLinkname() {
        return linkname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_link.linkName
     *
     * @param linkname the value for t_link.linkName
     *
     * @mbggenerated Mon Jan 28 09:38:24 CST 2019
     */
    public void setLinkname(String linkname) {
        this.linkname = linkname == null ? null : linkname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_link.linkPosition
     *
     * @return the value of t_link.linkPosition
     *
     * @mbggenerated Mon Jan 28 09:38:24 CST 2019
     */
    public String getLinkposition() {
        return linkposition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_link.linkPosition
     *
     * @param linkposition the value for t_link.linkPosition
     *
     * @mbggenerated Mon Jan 28 09:38:24 CST 2019
     */
    public void setLinkposition(String linkposition) {
        this.linkposition = linkposition == null ? null : linkposition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_link.picturePath
     *
     * @return the value of t_link.picturePath
     *
     * @mbggenerated Mon Jan 28 09:38:24 CST 2019
     */
    public String getPicturepath() {
        return picturepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_link.picturePath
     *
     * @param picturepath the value for t_link.picturePath
     *
     * @mbggenerated Mon Jan 28 09:38:24 CST 2019
     */
    public void setPicturepath(String picturepath) {
        this.picturepath = picturepath == null ? null : picturepath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_link.linkType
     *
     * @return the value of t_link.linkType
     *
     * @mbggenerated Mon Jan 28 09:38:24 CST 2019
     */
    public Integer getLinktype() {
        return linktype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_link.linkType
     *
     * @param linktype the value for t_link.linkType
     *
     * @mbggenerated Mon Jan 28 09:38:24 CST 2019
     */
    public void setLinktype(Integer linktype) {
        this.linktype = linktype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_link.linkUrl
     *
     * @return the value of t_link.linkUrl
     *
     * @mbggenerated Mon Jan 28 09:38:24 CST 2019
     */
    public String getLinkurl() {
        return linkurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_link.linkUrl
     *
     * @param linkurl the value for t_link.linkUrl
     *
     * @mbggenerated Mon Jan 28 09:38:24 CST 2019
     */
    public void setLinkurl(String linkurl) {
        this.linkurl = linkurl == null ? null : linkurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_link.pubTime
     *
     * @return the value of t_link.pubTime
     *
     * @mbggenerated Mon Jan 28 09:38:24 CST 2019
     */
    public Timestamp getPubtime() {
        return pubtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_link.pubTime
     *
     * @param pubtime the value for t_link.pubTime
     *
     * @mbggenerated Mon Jan 28 09:38:24 CST 2019
     */
    public void setPubtime(Timestamp pubtime) {
        this.pubtime = pubtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_link.pubTimeType
     *
     * @return the value of t_link.pubTimeType
     *
     * @mbggenerated Mon Jan 28 09:38:24 CST 2019
     */
    public Integer getPubtimetype() {
        return pubtimetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_link.pubTimeType
     *
     * @param pubtimetype the value for t_link.pubTimeType
     *
     * @mbggenerated Mon Jan 28 09:38:24 CST 2019
     */
    public void setPubtimetype(Integer pubtimetype) {
        this.pubtimetype = pubtimetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_link.expiredTime
     *
     * @return the value of t_link.expiredTime
     *
     * @mbggenerated Mon Jan 28 09:38:24 CST 2019
     */
    public Timestamp getExpiredtime() {
        return expiredtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_link.expiredTime
     *
     * @param expiredtime the value for t_link.expiredTime
     *
     * @mbggenerated Mon Jan 28 09:38:24 CST 2019
     */
    public void setExpiredtime(Timestamp expiredtime) {
        this.expiredtime = expiredtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_link.isShow
     *
     * @return the value of t_link.isShow
     *
     * @mbggenerated Mon Jan 28 09:38:24 CST 2019
     */
    public Integer getIsshow() {
        return isshow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_link.isShow
     *
     * @param isshow the value for t_link.isShow
     *
     * @mbggenerated Mon Jan 28 09:38:24 CST 2019
     */
    public void setIsshow(Integer isshow) {
        this.isshow = isshow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_link.orderId
     *
     * @return the value of t_link.orderId
     *
     * @mbggenerated Mon Jan 28 09:38:24 CST 2019
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_link.orderId
     *
     * @param orderid the value for t_link.orderId
     *
     * @mbggenerated Mon Jan 28 09:38:24 CST 2019
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_link.remark
     *
     * @return the value of t_link.remark
     *
     * @mbggenerated Mon Jan 28 09:38:24 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_link.remark
     *
     * @param remark the value for t_link.remark
     *
     * @mbggenerated Mon Jan 28 09:38:24 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_link.status
     *
     * @return the value of t_link.status
     *
     * @mbggenerated Mon Jan 28 09:38:24 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_link.status
     *
     * @param status the value for t_link.status
     *
     * @mbggenerated Mon Jan 28 09:38:24 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
    
    public Integer getExpiredTimeType() {
		return expiredTimeType;
	}

	public void setExpiredTimeType(Integer expiredTimeType) {
		this.expiredTimeType = expiredTimeType;
	}

}