package com.official.bean;

import java.sql.Timestamp;

import com.fasterxml.jackson.annotation.JsonFormat;

public class Logger {
    private Integer id;

    private String actionname;

    private String ip;

    private Integer userid;
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Timestamp happendate;

    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_logger.id
     *
     * @param id the value for t_logger.id
     *
     * @mbggenerated Sat Jan 26 13:31:43 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_logger.actionName
     *
     * @return the value of t_logger.actionName
     *
     * @mbggenerated Sat Jan 26 13:31:43 CST 2019
     */
    public String getActionname() {
        return actionname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_logger.actionName
     *
     * @param actionname the value for t_logger.actionName
     *
     * @mbggenerated Sat Jan 26 13:31:43 CST 2019
     */
    public void setActionname(String actionname) {
        this.actionname = actionname == null ? null : actionname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_logger.ip
     *
     * @return the value of t_logger.ip
     *
     * @mbggenerated Sat Jan 26 13:31:43 CST 2019
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_logger.ip
     *
     * @param ip the value for t_logger.ip
     *
     * @mbggenerated Sat Jan 26 13:31:43 CST 2019
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_logger.userId
     *
     * @return the value of t_logger.userId
     *
     * @mbggenerated Sat Jan 26 13:31:43 CST 2019
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_logger.userId
     *
     * @param userid the value for t_logger.userId
     *
     * @mbggenerated Sat Jan 26 13:31:43 CST 2019
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_logger.happenDate
     *
     * @return the value of t_logger.happenDate
     *
     * @mbggenerated Sat Jan 26 13:31:43 CST 2019
     */
    public Timestamp getHappendate() {
        return happendate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_logger.happenDate
     *
     * @param happendate the value for t_logger.happenDate
     *
     * @mbggenerated Sat Jan 26 13:31:43 CST 2019
     */
    public void setHappendate(Timestamp happendate) {
        this.happendate = happendate;
    }
}