package com.official.bean;

public class Position {
    //主键
    private Integer id;

    //位置名称
    private String positionname;

    //位置类型(0:图片链接,1:文本链接)
    private Integer positiontype;

   //备注
    private String remark;

    //排序值
    private Integer orderId;
   
    public Integer getOrderId() {
		return orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_position.id
     *
     * @param id the value for t_position.id
     *
     * @mbggenerated Mon Jan 28 09:38:24 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_position.postionName
     *
     * @return the value of t_position.postionName
     *
     * @mbggenerated Mon Jan 28 09:38:24 CST 2019
     */
    public String getPositionname() {
        return positionname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_position.postionName
     *
     * @param postionname the value for t_position.postionName
     *
     * @mbggenerated Mon Jan 28 09:38:24 CST 2019
     */
    public void setPositionname(String positionname) {
        this.positionname = positionname == null ? null : positionname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_position.positionType
     *
     * @return the value of t_position.positionType
     *
     * @mbggenerated Mon Jan 28 09:38:24 CST 2019
     */
    public Integer getPositiontype() {
        return positiontype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_position.positionType
     *
     * @param positiontype the value for t_position.positionType
     *
     * @mbggenerated Mon Jan 28 09:38:24 CST 2019
     */
    public void setPositiontype(Integer positiontype) {
        this.positiontype = positiontype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_position.remark
     *
     * @return the value of t_position.remark
     *
     * @mbggenerated Mon Jan 28 09:38:24 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_position.remark
     *
     * @param remark the value for t_position.remark
     *
     * @mbggenerated Mon Jan 28 09:38:24 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}