package com.official.bean;

public class VoteRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_record.id
     *
     * @mbggenerated Wed Oct 16 14:22:12 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_record.employeeId
     *
     * @mbggenerated Wed Oct 16 14:22:12 CST 2019
     */
    private Integer employeeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_record.compositionId
     *
     * @mbggenerated Wed Oct 16 14:22:12 CST 2019
     */
    private Integer compositionid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_record.id
     *
     * @return the value of vote_record.id
     *
     * @mbggenerated Wed Oct 16 14:22:12 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_record.id
     *
     * @param id the value for vote_record.id
     *
     * @mbggenerated Wed Oct 16 14:22:12 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_record.employeeId
     *
     * @return the value of vote_record.employeeId
     *
     * @mbggenerated Wed Oct 16 14:22:12 CST 2019
     */
    public Integer getEmployeeid() {
        return employeeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_record.employeeId
     *
     * @param employeeid the value for vote_record.employeeId
     *
     * @mbggenerated Wed Oct 16 14:22:12 CST 2019
     */
    public void setEmployeeid(Integer employeeid) {
        this.employeeid = employeeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_record.compositionId
     *
     * @return the value of vote_record.compositionId
     *
     * @mbggenerated Wed Oct 16 14:22:12 CST 2019
     */
    public Integer getCompositionid() {
        return compositionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_record.compositionId
     *
     * @param compositionid the value for vote_record.compositionId
     *
     * @mbggenerated Wed Oct 16 14:22:12 CST 2019
     */
    public void setCompositionid(Integer compositionid) {
        this.compositionid = compositionid;
    }
}