package com.official.bean;

import java.sql.Timestamp;

import com.fasterxml.jackson.annotation.JsonFormat;

public class WebsiteContent {
    private Integer id;

    private Integer articleId;

    private Integer columnid;

    private String ip;

    private Integer visitcount;

    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Timestamp visitdate;

    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_website_content.id
     *
     * @param id the value for t_website_content.id
     *
     * @mbggenerated Fri Jan 25 14:30:38 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_website_content.article_Id
     *
     * @return the value of t_website_content.article_Id
     *
     * @mbggenerated Fri Jan 25 14:30:38 CST 2019
     */
    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_website_content.article_Id
     *
     * @param articleId the value for t_website_content.article_Id
     *
     * @mbggenerated Fri Jan 25 14:30:38 CST 2019
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }


    public Integer getColumnid() {
        return columnid;
    }


    public void setColumnid(Integer columnid) {
        this.columnid = columnid;
    }

    public String getIp() {
        return ip;
    }

    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    public Integer getVisitcount() {
        return visitcount;
    }

    public void setVisitcount(Integer visitcount) {
        this.visitcount = visitcount;
    }

    public Timestamp getVisitdate() {
        return visitdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_website_content.visitDate
     *
     * @param visitdate the value for t_website_content.visitDate
     *
     * @mbggenerated Fri Jan 25 14:30:38 CST 2019
     */
    public void setVisitdate(Timestamp visitdate) {
        this.visitdate = visitdate;
    }
}