package com.official.dao;

import com.official.bean.Column;
import com.official.bean.ColumnExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ColumnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_column
     *
     * @mbg.generated Thu Mar 19 10:58:50 CST 2020
     */
    long countByExample(ColumnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_column
     *
     * @mbg.generated Thu Mar 19 10:58:50 CST 2020
     */
    int deleteByExample(ColumnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_column
     *
     * @mbg.generated Thu Mar 19 10:58:50 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_column
     *
     * @mbg.generated Thu Mar 19 10:58:50 CST 2020
     */
    int insert(Column record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_column
     *
     * @mbg.generated Thu Mar 19 10:58:50 CST 2020
     */
    int insertSelective(Column record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_column
     *
     * @mbg.generated Thu Mar 19 10:58:50 CST 2020
     */
    List<Column> selectByExample(ColumnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_column
     *
     * @mbg.generated Thu Mar 19 10:58:50 CST 2020
     */
    Column selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_column
     *
     * @mbg.generated Thu Mar 19 10:58:50 CST 2020
     */
    int updateByExampleSelective(@Param("record") Column record, @Param("example") ColumnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_column
     *
     * @mbg.generated Thu Mar 19 10:58:50 CST 2020
     */
    int updateByExample(@Param("record") Column record, @Param("example") ColumnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_column
     *
     * @mbg.generated Thu Mar 19 10:58:50 CST 2020
     */
    int updateByPrimaryKeySelective(Column record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_column
     *
     * @mbg.generated Thu Mar 19 10:58:50 CST 2020
     */
    int updateByPrimaryKey(Column record);

    List<Column> findSonColumn( @Param("id") Integer id);

    List<Integer> selectSonId(@Param("id") Integer id);

    Integer selectParentId(@Param("id") Integer id);

    List<Column> fuzzySearch(@Param("columnname") String columnname);

    List<Column> selectAll();
}