package com.official.dao;

import com.official.bean.User_Role;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
@Mapper
public interface User_RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_role
     *
     * @mbggenerated Fri Jan 04 17:30:54 CST 2019
     */
    int deleteByPrimaryKey(Integer id);
    
    int deleteByUserId(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_role
     *
     * @mbggenerated Fri Jan 04 17:30:54 CST 2019
     */
    int insert(User_Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_role
     *
     * @mbggenerated Fri Jan 04 17:30:54 CST 2019
     */
    User_Role selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_role
     *
     * @mbggenerated Fri Jan 04 17:30:54 CST 2019
     */
    List<User_Role> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_role
     *
     * @mbggenerated Fri Jan 04 17:30:54 CST 2019
     */
    int updateByPrimaryKey(User_Role record);
}